version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    docker:
      - image: circleci/ruby:3.2.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run tests
          command: bundle exec rails test
      - run:
          name: Run build
          command: bundle exec rails assets:precompile
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy_spell_binder_fe:
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true
          app-name: spell-binder-fe
          maintenance-mode: false

workflows:
  version: 2
  example-workflow:
    jobs:
      - build_and_test
      - deploy_spell_binder_fe:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - main
